[target.xtensa-esp32-none-elf]
# runner = "espflash flash --monitor"
# increase the baud for faster flashing
runner = "espflash flash --monitor --chip esp32 --baud 460800"


[env]
ESP_LOG="info"

[build]
target = "xtensa-esp32s3-none-elf"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "alloc"] # alloc required for radio use
