[alias]
esp32   = "run --release --no-default-features --features=esp32 --target=xtensa-esp32-none-elf"
esp32s3 = "run --release --no-default-features --features=esp32s3 --target=xtensa-esp32s3-none-elf"
# esp32c2 = "build --release --no-default-features --features=esp32c2 --target=riscv32imc-unknown-none-elf"
# esp32c3 = "build --release --no-default-features --features=esp32c3 --target=riscv32imc-unknown-none-elf"
# esp32c6 = "build --release --no-default-features --features=esp32c6 --target=riscv32imac-unknown-none-elf"
# esp32h2 = "build --release --no-default-features --features=esp32h2 --target=riscv32imac-unknown-none-elf"

[target.'cfg(all(any(target_arch = "riscv32", target_arch = "xtensa"), target_os = "none"))']
runner = "espflash flash --monitor --baud 460800"

[env]
ESP_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]
# default required by rust-analyzer
target="xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"] # alloc required for radio use
